#!/usr/bin/env python3
"""
Derive the E₀^{iid}(ρ) formula from the general definition to verify equivalence.

Starting from:
E₀^{iid}(ρ) = -log₂ ∑_x Q(x) ∫_y W(y|x) [∑_x̄ Q(x̄) W(y|x̄)^{1/(1+ρ)} / W(y|x)^{1/(1+ρ)}]^ρ dy

For AWGN: W(y|x) = (1/π) exp(-|y - √SNR·x|²)

Goal: Show this equals the formula with change of variables y = z + √SNR·x
"""

print("="*80)
print("DERIVATION: E₀^{iid}(ρ) for AWGN Channel")
print("="*80)
print()

print("STEP 1: General formula")
print("-"*80)
print("E₀^{iid}(ρ) = -log₂ ∑_{x∈𝒳} Q(x) ∫_y W(y|x) [...]^ρ dy")
print()
print("where [...] = ∑_{x̄∈𝒳} Q(x̄) [W(y|x̄) / W(y|x)]^{1/(1+ρ)}")
print()

print("STEP 2: AWGN channel model")
print("-"*80)
print("W(y|x) = (1/π) exp(-|y - √SNR·x|²)")
print()
print("For real-valued 2-PAM: y, x ∈ ℝ, x ∈ {-1, +1}")
print("For complex: y, z ∈ ℂ (we'll use complex notation)")
print()

print("STEP 3: Substitute W(y|x) into the formula")
print("-"*80)
print()
print("W(y|x̄) / W(y|x) = exp(-|y - √SNR·x̄|²) / exp(-|y - √SNR·x|²)")
print("                 = exp(-|y - √SNR·x̄|² + |y - √SNR·x|²)")
print()

print("STEP 4: Change of variables")
print("-"*80)
print("Let z = y - √SNR·x  (shift to center noise at origin)")
print()
print("Then: y = z + √SNR·x")
print("      dy = dz  (Jacobian = 1)")
print()
print("Substituting:")
print("  y - √SNR·x̄ = z + √SNR·x - √SNR·x̄ = z + √SNR(x - x̄)")
print()

print("STEP 5: Rewrite W(y|x) in terms of z")
print("-"*80)
print("W(y|x) = (1/π) exp(-|y - √SNR·x|²)")
print("       = (1/π) exp(-|z|²)")
print()
print("W(y|x̄) = (1/π) exp(-|y - √SNR·x̄|²)")
print("       = (1/π) exp(-|z + √SNR(x - x̄)|²)")
print()

print("STEP 6: Compute the ratio")
print("-"*80)
print("[W(y|x̄) / W(y|x)]^{1/(1+ρ)}")
print()
print("= [(1/π) exp(-|z + √SNR(x-x̄)|²) / ((1/π) exp(-|z|²))]^{1/(1+ρ)}")
print()
print("= [exp(-|z + √SNR(x-x̄)|² + |z|²)]^{1/(1+ρ)}")
print()
print("Let's denote the exponent:")
print("  Δ(x,x̄,z) = -|z + √SNR(x-x̄)|² + |z|²")
print()
print("Then: [W(y|x̄)/W(y|x)]^{1/(1+ρ)} = exp[Δ(x,x̄,z)/(1+ρ)]")
print()

print("STEP 7: Substitute back into E₀ formula")
print("-"*80)
print()
print("E₀^{iid}(ρ) = -log₂ ∑_x Q(x) ∫_z W(z+√SNR·x|x) [∑_x̄ Q(x̄) exp(Δ/(1+ρ))]^ρ dz")
print()
print("            = -log₂ ∑_x Q(x) ∫_z (1/π)e^{-|z|²} [∑_x̄ Q(x̄) exp(Δ/(1+ρ))]^ρ dz")
print()

print("STEP 8: Compare with target formula")
print("-"*80)
print()
print("TARGET formula:")
print("E₀^{iid}(ρ) = -log₂ ∑_x Q(x)/π ∫_z e^{-|z|²} [∑_x̄ Q(x̄) ((1/π)e^{-|z+√SNR(x-x̄)|²})^{1/(1+ρ)}")
print("                                                           / ((1/π)e^{-|z|²})^{1/(1+ρ)}]^ρ dz")
print()

print("DERIVED formula:")
print("E₀^{iid}(ρ) = -log₂ ∑_x Q(x)/π ∫_z e^{-|z|²} [∑_x̄ Q(x̄) exp(Δ/(1+ρ))]^ρ dz")
print()

print("where Δ(x,x̄,z) = -|z + √SNR(x-x̄)|² + |z|²")
print()

print("STEP 9: Verify the exponent in target formula")
print("-"*80)
print()
print("Target ratio inside [...]:")
print("  [(1/π)e^{-|z+√SNR(x-x̄)|²}]^{1/(1+ρ)} / [(1/π)e^{-|z|²}]^{1/(1+ρ)}")
print()
print("= [(1/π)^{1/(1+ρ)} · e^{-|z+√SNR(x-x̄)|²/(1+ρ)}] / [(1/π)^{1/(1+ρ)} · e^{-|z|²/(1+ρ)}]")
print()
print("= e^{[-|z+√SNR(x-x̄)|² + |z|²]/(1+ρ)}")
print()
print("= e^{Δ(x,x̄,z)/(1+ρ)}")
print()
print("✓ This matches our derived formula!")
print()

print("="*80)
print("CONCLUSION")
print("="*80)
print()
print("✓✓✓ YES! The formulas are IDENTICAL. ✓✓✓")
print()
print("The target formula from your prompt:")
print("  E₀^{iid}(ρ) = -log₂ ∑_x (Q(x)/π) ∫ e^{-|z|²} [inner]^ρ dz")
print()
print("is exactly the same as the general definition:")
print("  E₀^{iid}(ρ) = -log₂ ∑_x Q(x) ∫ W(y|x) [inner]^ρ dy")
print()
print("obtained by the change of variables z = y - √SNR·x")
print()
print("Key insight:")
print("  - Original integral over y with weight W(y|x) = (1/π)e^{-|y-√SNR·x|²}")
print("  - After substitution z = y - √SNR·x:")
print("    • W(y|x) → (1/π)e^{-|z|²}  (noise centered at origin)")
print("    • dy → dz")
print("    • Q(x) factor combines with (1/π) to give Q(x)/π")
print()
